# Generated by Django 3.1.7 on 2021-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='static/uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.PositiveIntegerField()),
                ('pinned', models.BooleanField()),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('reply_to', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField()),
                ('images', models.ManyToManyField(to='cforums.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('pinned', models.BooleanField()),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('images', models.ManyToManyField(to='cforums.Image')),
            ],
        ),
    ]
